name: app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.4
  auto_size_text: ^3.0.0
  keyboard_dismisser: ^2.0.1
  google_fonts: 2.2.0
  json_serializable: ^6.1.4
  dio: ^4.0.4
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.5+2
  get_it: ^7.1.4
  intl: ^0.17.0
  lottie: ^1.2.1
  carousel_slider: ^4.0.0
  localstorage: ^4.0.0+1
  flutter_feather_icons: ^2.0.0+1
  google_sign_in: ^5.2.4
  flutter_native_splash: ^1.1.9
  cached_network_image: ^3.2.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  url_launcher: ^6.0.20
  mask_text_input_formatter: ^2.1.0
  flutter_phoenix: ^1.0.0
  restart_app: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/

flutter_native_splash:
  color: E91D2C
  image: assets/images/splash.png
